# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "Niello"
license = "MIT"
licenselink = "https://github.com/guangmean/Niello/blob/master/LICENSE"
description = "A Dark Theme for Hugo"
homepage = "https://github.com/guangmean/Niello"
tags = ["blog", "Syntax highlighting", "Highlight.js", "Dark"]
features = ["blog"]
min_version = "0.41"

[author]
  name = "guangmean"
  homepage = "https://github.com/guangmean/Niello"

# If porting an existing theme
[original]
  name = ""
  homepage = ""
  repo = ""
